name: Artifacts Comparison

on:
  workflow_dispatch:

jobs:
  medium-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          dd if=/dev/urandom of=1mb-random bs=1M count=1
      - uses: actions/upload-artifact@v4
        name: "Upload 1MB - v4"
        with:
          name: 1mb-v4
          path: 1mb-random
          compression-level: 0
      - uses: actions/upload-artifact@v3
        name: "Upload 1MB - v3"
        with:
          name: 1mb-v3
          path: 1mb-random
      - uses: actions/download-artifact@v4
        name: "Download 1MB - v4"
        with:
          name: 1mb-v4
          path: 1mb-v4
      - uses: actions/download-artifact@v3
        name: "Download 1MB - v3"
        with:
          name: 1mb-v3
          path: 1mb-v3
